### ISSUE TITLE
Crash on startup, ClassNotFound: moonlight/api/item/fuelItem

### ISSUE THREAD

**Issue by Aquaeyes** [AstralOrdana/Spelunkery#41]
**Describe the bug:**
Caused by: java.lang.NoClassDefFoundError: net/mehvahdjukaar/moonlight/api/item/FuelItem
	at com.ordana.spelunkery.Spelunkery.commonInit(Spelunkery.java:39)
	at com.ordana.spelunkery.fabric.SpelunkeryFabric.onInitialize(SpelunkeryFabric.java:31)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: both BETA-0.1.11 and the build of the latest commit. (BETA-0.1.16)
Moonlight Lib version: 1.19.2-2.2.3
Supplementaries: 1.19.2-2.2.50 (also occurs with the mod not present)
Fabric API / QSL / Forge version: qfapi-4.0.0-beta.28_qsl-3.0.0-beta.29_fapi-0.73.2_mc-1.19.2

**Other mods:**
N/A

**Logs:**

latest.log: https://mclo.gs/IVedYZ2

**Comment by AstralOrdana** [comment]
`Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)`

your moonlight is out of date

**Comment by Aquaeyes** [comment]
Ah heck, thank you. Looks like their 'latest' modrinth version is out of date, ack.
