### ISSUE TITLE
Error Upon World Creation

### ISSUE THREAD

**Issue by ereese99** [AstralOrdana/Spelunkery#44]
java.lang.IllegalStateException: Item: oreganized:silver_ingot does not exist
	at net.minecraft.class_3957.method_17879(class_3957.java:33)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_3957.method_17736(class_3957.java:33)
	at net.minecraft.class_3957.method_8121(class_3957.java:11)
	at net.minecraft.class_1863.method_17720(class_1863.java:135)
	at net.minecraft.class_1863.method_20705(class_1863.java:56)
	at net.minecraft.class_1863.method_18788(class_1863.java:35)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.class_525.method_31130(class_525.java:158)
	at net.minecraft.class_528.method_43462(class_528.java:147)
	at net.minecraft.class_528.<init>(class_528.java:91)
	at net.minecraft.class_526.method_25426(class_526.java:65)
	at net.minecraft.class_437.method_41843(class_437.java:389)
	at net.minecraft.class_437.method_25423(class_437.java:380)
	at net.minecraft.class_310.method_1507(class_310.java:1035)
	at net.minecraft.class_442.method_19861(class_442.java:160)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:343)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.handler$ghk000$handleWaitEventsTimeout(RenderSystem.java:1983)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by AstralOrdana** [comment]
revert to the previous version of Moonlight Lib
